// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcxIOzktM-r4evptu2rJtjRntv3y2B_6E',
    appId: '1:976890515293:web:53f857cca2b41e678f62b4',
    messagingSenderId: '976890515293',
    projectId: 'authtutorial-b76bf',
    authDomain: 'authtutorial-b76bf.firebaseapp.com',
    storageBucket: 'authtutorial-b76bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDprmfb76bGGubuUNrJnSINPM68uCiM6og',
    appId: '1:976890515293:android:13feb28ad613f5158f62b4',
    messagingSenderId: '976890515293',
    projectId: 'authtutorial-b76bf',
    storageBucket: 'authtutorial-b76bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz5NUm9xg4jetKYjWX14QbiXtOqieKolQ',
    appId: '1:976890515293:ios:0dd4e96a199ed15b8f62b4',
    messagingSenderId: '976890515293',
    projectId: 'authtutorial-b76bf',
    storageBucket: 'authtutorial-b76bf.appspot.com',
    iosClientId: '976890515293-gbrnenc0uu8588cb12qluuqfln6skood.apps.googleusercontent.com',
    iosBundleId: 'com.example.testingflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz5NUm9xg4jetKYjWX14QbiXtOqieKolQ',
    appId: '1:976890515293:ios:8edcaf280ca7c5058f62b4',
    messagingSenderId: '976890515293',
    projectId: 'authtutorial-b76bf',
    storageBucket: 'authtutorial-b76bf.appspot.com',
    iosClientId: '976890515293-67poeknf5m3v57dqpu98uaaf97u3imk3.apps.googleusercontent.com',
    iosBundleId: 'com.example.testingflutter.RunnerTests',
  );
}
